### ISSUE TITLE
Bearings and Files 

### ISSUE THREAD

**Issue by mgiaco** [mosfet/kossel-minimax#1]
Hello do I need 600mm linear bearings for this printer or 800mm? I can't open the files.  Is it possible to convert the files to step? 

Thanks Mathias

**Comment by mgiaco** [comment]
Second question is it possible that you upload some detailed pictures,  I want to build that printer it looks very nice.  Thanks

**Comment by mosfet** [comment]
I use 800mm linear rails because I have 1000mm long vertical extrusions, and they work fine but are a bit long. If I were building it again, I would actually shorten both the vertical extrusion length to 800mm and use 600mm rails - I have yet to use anywhere near the full print height, and I'm not sure the increase in price is worth it, for me.

I'm sure you've seen all the pics from https://github.com/mosfet/kossel-minimax/tree/master/preview but there are a few more posted here, of a couple different builds: https://imgur.com/a/vriql#0

**Comment by mgiaco** [comment]
Thanks for your help. Is it possible that you save the Solidworks Assembled File in a Step or IGES format. So I can open it without Solidworks for assembling. 

thanks
kind regards,
Mathias

**Comment by mosfet** [comment]
I generally keep them in SW format since they have multiple configurations
(motor covers with and without room for enclosure clamps, extra pieces from
here and there) and parameters (i.e. can adjust the size of things and
everything else also automatically adjusts).

However, I did export all the files to STEP files and uploaded them to the
STEP folder. Hopefully they'll include all configuration data and can be
adjusted easily if you need to.

**Comment by mgiaco** [comment]
Thanks, it works fine. But the assembled parts are missing :-( so i searched for some other tools today. Now I found the eDrawings Tools on the Solidworks Website today. And the great thing is that this viewer could be used for free. But it seems that some of the assembled files aren´t up to date. The file assembled_extruder_dd.SLDASM as an example could not be opened with this viewer something seems to be not up to date. It would be great if you can fix that but the main file assembled complete works fine no I can build it if i get the printed parts.
 
Really really big thanks for your support and for your awesome work. Thanks for sharing it.

best regards from austria,
Mathias

**Comment by mgiaco** [comment]
Hello,

Sorry that I ask you again. Is it possible that you do a refresh on the Solidworks Files? I cannot update the Files with the viewer only. But there seems to be something wrong so I cannot open some assembled files. Is it possible that you save the assembled as step or iges also?

thanks a lot.
best regards

**Comment by mosfet** [comment]
I reposted all the converted files in both STEP and IGES format, including the assemblies, so you should have everything.

**Comment by mgiaco** [comment]
You are really awesome. 
many many thanks for that commit
Mathias
